obstacle_range: 2.5
raytrace_range: 2.5
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
robot_radius: 0.1408
inflation_radius: 0.1

observation_sources: laser_scan_sensor sonar_scan_sensor

laser_scan_sensor: {sensor_frame: IR_link, data_type: LaserScan, topic: /sensor_msgs/LaserScan, marking: true, clearing: true}

sonar_scan_sensor: {sensor_frame: sonar_link, data_type: SonarScan, topic: /sensor_msgs/SonarScan, marking: true, clearing: true}
