# gazebo_ros_control_params.yaml
/gazebo_ros_control:   
  pid_gains:
    left_wheel_joint:
      p: 10.0
      i: 5.0 
      d: 1.0
      
    right_wheel_joint:
      p: 10.0
      i: 5.0 
      d: 1.0    
